# Generated by Django 4.0.4 on 2022-10-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferapp', '0002_remove_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
