# Generated by Django 4.0.4 on 2022-11-13 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ferapp', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
